### ISSUE TITLE
Endpoint de Login devuelve parte del usuario solamente, lo demas en null o en 0

### ISSUE THREAD

**Issue by fzunigad** [rodedition/WS_APP_SAFE#17]
user:"`{"idusuario":0,
"runusuario":null,
"nombresusuario":"Antonio",
"appaterno":"Vald��s",
"apmaterno":"Soto",
"fnacimientousuario":null,
"sexousuario":null,
"telusuario":null,
"mailusuario":null,
"estadousuario":0,
"claveusuario":null,
"perfilidperfil":1,
"clienteidcliente":0}"`

**Comment by rodedition** [comment]
Devuelve con datos solo los necesarios para agregar a la página principal (Nombre del usuario, perfil). Si necesitas más datos o todos, favor avisar.

**Comment by fzunigad** [comment]
Hola, ideal tener todos los campos por si las moscas (excepto la clave por seguridad)

Gracias

**Comment by rodedition** [comment]
Cambio solicitado a git.

**Comment by rodedition** [comment]
Sorry, queda disponible en git los cambios.
