### ISSUE TITLE
Crear y actualizar solicitud de evaluacion en terreno no funcionan

### ISSUE THREAD

**Issue by fzunigad** [rodedition/WS_APP_SAFE#22]

**Comment by rodedition** [comment]
La función crear funciona correctamente. Favor revisar código aplicado.

![image](https://user-images.githubusercontent.com/44207727/49334620-154e2d80-f5b9-11e8-81ec-359ddeb5dd71.png)

**Comment by rodedition** [comment]
Metodo Actualizar corregido, el problema era que en el metodo del dao esta apuntando al eliminar. subido a github.
