### ISSUE TITLE
el metodo usuarios/login arroja error HTTP 500 

### ISSUE THREAD

**Issue by rdcklinux** [rodedition/WS_APP_SAFE#26]
al tratar de hacer un request post a este método arroja un error.
mirando el log informa este error:
java.sql.SQLException: Nombre de columna no válido 	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3757) 	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:264) 	at oracle.jdbc.driver.GeneratedResultSet.getLong(GeneratedResultSet.java:558) 	at weblogic.jdbc.wrapper.ResultSet_oracle_jdbc_driver_ForwardOnlyResultSet.getLong(Unknown Source) 	at com.ws_safe.dao.UsuariosDAOImpl$1.execute(UsuariosDAOImpl.java:57) 	at com.ws_safe.dao.UsuariosDAOImpl$1.execute(UsuariosDAOImpl.java:43)

en el ws el código intenta obtener estos campos inexistentes en lo que devuelve el procedure desde oracle.

usuarios.setIdusuario(rs.getLong("ID_USUARIO"));
usuarios.setRunusuario(rs.getString("RUN_USUARIO"));
usuarios.setNombresusuario(rs.getString("NOMBRES_USUARIO"));
usuarios.setAppaterno(rs.getString("AP_PATERNO"));
usuarios.setApmaterno(rs.getString("AP_MATERNO"));
usuarios.setFnacimientousuario(rs.getString("F_NACIMIENTO_USUARIO"));
usuarios.setSexousuario(rs.getString("SEXO_USUARIO"));
usuarios.setTelusuario(rs.getString("TEL_USUARIO"));
usuarios.setMailusuario(rs.getString("MAIL_USUARIO"));
usuarios.setEstadousuario(rs.getLong("ESTADO_USUARIO"));
usuarios.setPerfilidperfil(rs.getLong("PERFIL_ID_PERFIL"));
usuarios.setClienteidcliente(rs.getLong("CLIENTE_ID_CLIENTE"));

**Comment by fzunigad** [comment]
Ya se actualizó el package de usuario. cerrar

**Comment by rdcklinux** [comment]
solucionado!
