### ISSUE TITLE
Fechas y horas

### ISSUE THREAD

**Issue by rdcklinux** [rodedition/WS_APP_SAFE#29]
* Se debe devolver desde el webservice para los campos *fechas* solo la fecha (DD-MM-YYYY) y para los campos hora solo la hora (HH:MM).
* Al enviar una *hora* o *fecha* debe tratarla adecuadamente para que se guarde correctamente en la base de datos. 
* Para datos solo de *hora* no importa la fecha, puede ser la fecha actual.

**Comment by rodedition** [comment]
se explican los formatos para poder enviar y recibir datos.
