### ISSUE TITLE
Al crear un nuevo registro el ws no devuelve el ID

### ISSUE THREAD

**Issue by rdcklinux** [rodedition/WS_APP_SAFE#4]
Al crear un registro a través del webservice debería retornar el id del registro insertado para todas las entidades. se sugiere crear un registro como este

{"id": 3454, "entity": "Cliente"}

donde **entity** es el nombre de la clase e **id** el identificador del objeto.

**Comment by rodedition** [comment]
se agregan en todos los agregar
