### ISSUE TITLE
Falta a entidad de evaluación

### ISSUE THREAD

**Issue by rdcklinux** [rodedition/WS_APP_SAFE#5]
Falta la entidad de evaluación que relaciona la solicitud en terreno y las observaciones del usuario Ingeniero y Supervisor.
Se debe definir métodos del ws para consultar estos datos.

se debería poder acceder a una evaluación con el id de la solicitud
se debería disponer del id de la evaluación en la solicitud
si la solicitud no tiene evaluaciones debería estar con null el campo para filtrarlo en la aplicación y no mostrar solicitudes que aun no se han iniciado.

**Comment by rodedition** [comment]
Realizado y disponible en gib hub.
